[package]
name = "solarhorizon/rodux-hooks"
description = "Roact hooks for Rodux"
authors = ["SolarHorizon"]
version = "0.3.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
Roact = "roblox/roact@1.4"
